title: Wahidul Islam
logo: /assets/img/headshot_circle.png
description: (MSc & BSc in Microbiology (Thesis Track | Faculty First Student).
Department of Microbiology, Jagannath University, Dhaka, Bangladesh. 
Research Interests: Infectious Diseases | Molecular Bioscience | Public Health.
Aspiring Ph.D. Students | Focus area: Molecular Infectious Diseases. 
LinkedIn | ORCID | Google Scholar | GitHub | Portfolio | ResearchGate. 
Email: wahidulislam.me@gmail.com, Contact No: +880 1860-797928.) 
show_downloads: false
theme: jekyll-theme-minimal
