title: Wahidul Islam
logo: /assets/img/headshot_circle.png
description: Hello I am Md. Wahidul Islam, here is my simple portfolio website; thank you for visiting.
show_downloads: false
theme: jekyll-theme-minimal
